### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded - esp8266

### ISSUE THREAD

**Issue by fizista** [fizista/micropython-scron#1]
For the micropython "esp8266" port, there is a problem with the number of possible recursions.
The problem may occur when using decorators.

Example of an error message:
```
Traceback (most recent call last):
  File "lib/scron/week.py", line 120, in _next_step
  File "lib/scron/week.py", line 72, in run_callbacks
  File "lib/scron/scount.py", line 445, in run_callbacks
  File "lib/scron/scount.py", line 441, in get_exactly
  File "lib/scron/scount.py", line 441, in get_exactly
  File "lib/scron/scount.py", line 441, in get_exactly
  File "lib/scron/scount.py", line 441, in get_exactly
  File "lib/scron/scount.py", line 437, in get_exactly
  File "lib/scron/decorators.py", line 52, in wrapper
  File "lib/scron/base.py", line 101, in remove
  File "lib/scron/base.py", line 90, in _first_step
  File "lib/scron/week.py", line 61, in get_next_pointer
  File "lib/scron/scount.py", line 419, in get_next_pointer
  File "lib/scron/scount.py", line 417, in get_next_pointer
  File "lib/scron/scount.py", line 407, in get_nearest
  File "lib/scron/scount.py", line 405, in get_nearest
  File "lib/scron/scount.py", line 402, in get_nearest
  File "lib/scron/scount.py", line 389, in get_first
  File "lib/scron/scount.py", line 120, in items
  File "lib/scron/scount.py", line 107, in get_value
  File "lib/scron/scount.py", line 101, in __init__
RuntimeError: maximum recursion depth exceeded
```

It is possible to estimate approximately the number of recursions using the code below:
```
def a():
    b()

def b():
    a()

a()
```
For esp8266 possible recursions are possible: 24
For esp32 possible recursions are possible: 51

There are several places where the code has to be rewritten in order to reduce the number of recursions.

Methods that contain unnecessary recursion:

- [x] scount.py - SimpleCounter.add
- [x] scount.py - SimpleCounter.remove
- [x] scount.py - SimpleCounter.get_next_pointer
- [x] scount.py - ~~SimpleCounter.run_callbacks~~ (fixed)

**Comment by fizista** [comment]
It's all rewritten.
